### ISSUE TITLE
Bounds on orientation, e.g., SO(2)

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#663]
**[Original report](https://bitbucket.org/ompl/ompl/issue/542) by W M (Bitbucket: [wxmerkt](https://bitbucket.org/wxmerkt), GitHub: [wxmerkt](https://github.com/wxmerkt)).**

----------------------------------------

Hi,

We have been using OMPL for a long time and setting the SE\(2\)/SE\(3\) bounds \(in a compound state space - it is the first subspace\). The bounds are only set for the translation component \(and `getDimension` on SE\(2\)/SE\(3\) only returns the size of the first subspace, not the compound state space\), not for the orientation \(which makes sense for SO\(3\)\). However, we have been wondering whether support can be added for bounds on orientation?

As a background, our use case: We are using SE\(2\)\+RN and SE\(3\)\+RN subspaces in compound state spaces and want to restrict orientation, e.g., yaw in SO\(2\) to a certain range and pitch and roll in SE\(3\) to a certain range. As a workaround, we are treating SE\(2\)\+RN simply as RN but are reluctant to do the same for SE\(3\)\+RN.

Thank you very much for all your insights,  
Wolfgang

**Comment by mikebentley15** [comment]
One way to implement uniform sampling would be to use the current approach for uniform sampling and reject samples that do not satisfy the orientation constraints.  In other words, implement rejection sampling.  This may be a bad approach if you heavily restrict the orientation space since that would result in many rejected samples.

What is the current approach in SO(3)?  Is it an angle-axis formulation?  Or something else?

I don't currently have a use case for this, but I agree that it could be a useful feature in some situations.

**Comment by marios-stam** [comment]
Hello, I am currently facing the same problem, I load a robot and the environment as meshes to the SE3RigidBodyPlanning and I am trying to figure out a way to set limits to the rotation of the robot(e.g yaw, pith roll only from -45 to 45 degrees)  or use only 2 axes. Did you have any progress on that or any other suggestions?

**Comment by zkingston** [comment]
As an "easy" solution, you can implement a sampler that uses the Euler angle bounds that you desire (e.g., with [eulerRPY](http://ompl.kavrakilab.org/classompl_1_1RNG.html#a2a356471002c4ffe5dbf5aa5bfea9ef6), and then reject angles outside these bounds (or implement it as a custom R^3 space with the correct interpolation). We currently do not have any plans to implement generic SO(3) constrained sampling at this time, but would welcome this contribution.
