### ISSUE TITLE
Different tolerance for each term of constraint?

### ISSUE THREAD

**Issue by arjung128** [ompl/ompl#896]
Is it possible to set a different tolerance for each term of the constraint?

Additionally, can constraints be entirely positive, e.g. `(y_target - y_current)^2`, or is it better if they are allowed to be negative, e.g. `(y_target - y_current)`?

Thanks!

**Comment by zkingston** [comment]
If you mean the `ompl::base::Constraint` interface for constrained planning and want to combine constraints through a `ompl::base::ConstraintIntersection`, there is no built in weighting interface to change the relative "value" of the constraints so that tolerances can be per constraint. You will have to tune the magnitude of the functions so that the L2 norm of the constraint is under the tolerance you desire. Alternatively, you can overload `distance` and `isSatisfied` on the constraint function class to whatever is appropriate for your use-case.
